[versions]

compileSdk = "35"
android-plugin = "8.8.0"
kotlin = "2.1.10"

[libraries]

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]

android-library = { id = "com.android.library", version.ref = "android-plugin" }
