package dev.tesserakt.sparql.runtime.query

import dev.tesserakt.sparql.QueryStatistics
import dev.tesserakt.sparql.runtime.collection.MappingArray
import dev.tesserakt.sparql.runtime.collection.MappingArrayHint
import dev.tesserakt.sparql.runtime.evaluation.*
import dev.tesserakt.sparql.runtime.evaluation.context.QueryContext
import dev.tesserakt.sparql.runtime.evaluation.mapping.Mapping
import dev.tesserakt.sparql.runtime.evaluation.mapping.hashable
import dev.tesserakt.sparql.runtime.query.jointree.JoinTree
import dev.tesserakt.sparql.runtime.stream.*
import dev.tesserakt.sparql.util.Cardinality
import dev.tesserakt.sparql.util.Counter
import dev.tesserakt.sparql.util.OneCardinality
import kotlin.jvm.JvmInline

class OptionalState private constructor(
    private val inner: MutableJoinState,
    private val optional: OptionalBlock,
    private val filters: List<FilterExpression>,
): MutableJoinState {

    @JvmInline
    private value class OptionalBlock(
        val state: MutableJoinState,
    ) {

        fun process(delta: DataDelta) {
            state.process(delta)
        }

        fun stats(context: QueryContext, granularity: QueryStatistics.Granularity): Statistics {
            return Statistics.DescriptionElement(
                description = "OPTIONAL",
                inner = state.stats(context, granularity),
            )
        }

        fun optionalJoin(stream: Stream<MappingDelta>): Stream<MappingDelta> {
            return stream.transform(state.cardinality.coerceAtLeast(OneCardinality)) { element ->
                // we need to return the original element if we don't actually yield any results of our own
                state.join(element).orElse(element)
            }
        }

        fun optionalJoin(delta: DataDelta, stream: Stream<MappingDelta>): Stream<MappingDelta> {
            val peeked = state.peek(delta)
            return if (peeked.hasZeroCardinality()) {
                // this data change does not affect us in a meaningful way, so we can do a more direct join
                stream.transform(state.cardinality.coerceAtLeast(OneCardinality)) { element ->
                    // we need to return the original element if we don't actually yield any results of our own
                    state.join(element).orElse(element)
                }
            } else {
                // we need to create a 'combined' intermediate state, which only contains mapping 'additions' for
                //  us to join with
                val base = state
                    .join(MappingAddition(Mapping.EMPTY, null))
                    .chain(peeked)
                    // we have to 'simplify' these combined results immediately, as otherwise `optionalJoin` might
                    //  misbehave when an addition - deletion combo 'consume' each other and thus incorrectly emit
                    //  no results
                    .simplified()
                // the result should now only be mapping additions
                stream.transform(state.cardinality.coerceAtLeast(OneCardinality)) { element ->
                    // we need to return the original element if we don't actually yield any results of our own
                    join(base, streamOf(element)).orElse(element)
                }
            }

        }

        /**
         * Checks to see if different results are generated by applying this [delta]
         */
        fun isInvalidatedBy(delta: DataDelta): Boolean {
            // acts as a counter that can go below 0
            return state.peek(delta).iterator().hasNext()
        }

    }

    constructor(
        inner: MutableJoinState,
        optional: JoinTree,
        filters: List<FilterExpression>,
    ): this(
        inner = inner,
        optional = OptionalBlock(
            state = optional
        ),
        filters = filters.filter { filter ->
            val innerOverlap = filter.bindings.intersectSize(inner.properties.maximum)
            val optionalOverlap = filter.bindings.intersectSize(optional.properties.maximum)
            // we only want to apply this filter where it makes sense the most;
            // in order to satisfy this requirement,
            // neither side has *none* of the required bindings
            innerOverlap != 0 && optionalOverlap != 0 &&
            // nor do either of them have *all* of the bindings, as the filter would be applied there
            //  instead
            innerOverlap != filter.bindings.size && optionalOverlap != filter.bindings.size &&
            // but combined they do
            filter.bindings in (inner.properties.maximum + optional.properties.maximum)
        },
    )

    override val properties = MutableJoinState.Properties(
        guaranteed = inner.properties.guaranteed,
        maximum = inner.properties.maximum + optional.state.properties.maximum,
    )

    private var indexedBindings = BindingIdentifierSet.EMPTY
    private var arrayHint = MappingArrayHint()
    private var state = MappingArray(indexedBindings, arrayHint)

    override val cardinality: Cardinality
        get() = state.cardinality

    init {
        // we have to construct our initial state
        val base: Stream<MappingDelta> = inner
            .join(MappingAddition(Mapping.EMPTY, null))
            // required for our `check` that only expects mapping additions; if we're dealing with a mapping
            //  deletion, it should consume the corresponding additions before we do the optional join chain
            .simplified()
        val final = optional.optionalJoin(base)
        // these should all be mapping additions
        final.forEach { delta ->
            check(delta is MappingAddition)
            if (filters.all { it.test(delta.value) }) {
                state.add(delta.value)
            }
        }
    }

    override fun join(delta: MappingDelta): Stream<MappingDelta> {
        val origin = delta.origin
        return if (origin != null) {
            // we cannot use the `stateAfter` variant, as we do NOT want to join with new additions
            //  after having processed the deletion yet!
            val ignored = peek(origin)
            delta.mapToStream {
                state
                    .iter(delta.value)
                    .let { stream ->
                        stream.remove(ignored.mappedNonNull { delta -> delta.value.takeIf { delta is MappingDeletion } })
                    }
                    .join(delta.value)
            }
        } else {
            delta.mapToStream { mapping -> state.join(mapping) }
        }
    }

    override fun reindex(
        bindings: BindingIdentifierSet,
        hint: MappingArrayHint
    ) {
        if (this.indexedBindings == bindings && this.arrayHint == hint) {
            return
        }
        this.indexedBindings = bindings
        this.arrayHint = hint
        val newArray = MappingArray(indexedBindings, arrayHint)
        state.iter().forEach {
            newArray.add(it)
        }
        state = newArray
    }

    override fun peek(delta: DataDelta): OptimisedStream<MappingDelta> {
        // two options: either the delta affects any of our OPTIONAL blocks, in which case we have to re-evaluate
        //  the results, or the delta (at most) only affects our regular inner state, to which we can apply
        //  regular join semantics
        val affectsOptional = optional.isInvalidatedBy(delta)
        return if (!affectsOptional) {
            optional.optionalJoin(inner.peek(delta))
                .filtered { delta -> filters.all { it.test(delta.value) } }
                .optimisedForSingleUse()
        } else {
            // we have to recalculate the entire state from nothing, combined with the impact of the peeked change,
            //  and have that ripple through all our optionals
            val newState = stateAfter(delta)
            // our peeked delta is the difference between this new state and our existing state
            val c1 = Counter(state.iter().mapped { it.hashable() })
            val c2 = Counter(newState.iter().mapped { it.hashable() })
            val total = c1.current + c2.current
            val diffs = total.associateWith { c2[it] - c1[it] }
            CollectedStream(
                data = diffs.asIterable().flatMap { (mapping, count) ->
                    when {
                        count == 0 -> emptyList()
                        count > 0 -> {
                            List(count) { MappingAddition(mapping.inner, delta) }
                        }
                        else -> {
                            List(-count) { MappingDeletion(mapping.inner, delta) }
                        }
                    }
                }
            )
        }
    }

    override fun process(delta: DataDelta) {
        state = stateAfter(delta)
        // invalidating the cache as we're changing our internal state
        cached = null
        inner.process(delta)
        optional.process(delta)
    }

    override fun stats(
        context: QueryContext,
        granularity: QueryStatistics.Granularity
    ): Statistics {
        val inner = Statistics.JoinedElement(
            left = inner.stats(context, granularity),
            right = optional.stats(context, granularity)
        )
        if (granularity isAtLeast QueryStatistics.Granularity.DETAILED && filters.isNotEmpty()) {
            return Statistics.DescriptionElement(
                description = "Filtered\n${filters.joinToString("\n")}",
                inner = inner,
            )
        }
        return Statistics.SelectiveElement(
            cardinality = cardinality,
            inner = inner,
        )
    }

    /**
     * The last cached value generated by [stateAfter]. Gets invalidated if internal state is
     *  altered (through [process]).
     */
    private var cached: Pair<DataDelta, MappingArray>? = null

    private fun stateAfter(delta: DataDelta): MappingArray {
        val cached = cached
        if (cached != null && cached.first == delta) {
            return cached.second
        }
        val base: Stream<MappingDelta> = inner
            .join(MappingAddition(Mapping.EMPTY, null))
            .chain(inner.peek(delta))
            // required for our `check` that only expects mapping additions; if we're dealing with a mapping
            //  deletion, it should consume the corresponding additions before we do the optional join chain
            .simplified()
        val final = optional.optionalJoin(delta, base)
        // these should all be mapping additions
        val result = MappingArray(indexedBindings, arrayHint)
        final.forEach { delta ->
            check(delta is MappingAddition)
            if (filters.all { it.test(delta.value) }) {
                result.add(delta.value)
            }
        }
        // caching our result so subsequent evaluations can reuse it
        this.cached = delta to result
        return result
    }

}

/**
 * Simplifies a stream of deltas, removing opposing changes, potentially reducing the total number of elements.
 */
private fun Stream<MappingDelta>.simplified(): CollectedStream<MappingDelta> {
    val combined = this
        // we need to make it hashable for `groupingBy` to work correctly
        .groupingBy { it.value.hashable() }
        .fold({ _, _ -> 0 }) { _, count, delta ->
            val d = if (delta is MappingAddition) 1 else -1
            count + d
        }
    return CollectedStream(
        data = combined.asIterable().flatMap { (mapping, count) ->
            when {
                count == 0 -> emptyList()
                count > 0 -> {
                    List(count) { MappingAddition(mapping.inner, null) }
                }
                else -> {
                    List(-count) { MappingDeletion(mapping.inner, null) }
                }
            }
        }
    )
}
