package dev.tesserakt.sparql.runtime.common.types

import dev.tesserakt.rdf.types.Quad
import dev.tesserakt.sparql.runtime.node.CommonNode
import kotlin.jvm.JvmInline

data class Pattern(
    val s: Subject,
    val p: Predicate,
    val o: Object,
): CommonNode {

    sealed interface Subject: CommonNode

    sealed interface Predicate: CommonNode

    sealed interface Object: CommonNode

    sealed interface NonRepeatingPredicate: Predicate

    sealed interface FixedPredicate: NonRepeatingPredicate

    sealed interface RepeatingPredicate: Predicate {
        val element: FixedPredicate
    }

    sealed interface Binding: Subject, NonRepeatingPredicate, Object {
        val name: String
    }

    /**
     * Bindings coming directly from an entered query
     */
    @JvmInline
    value class RegularBinding(override val name: String): Binding

    /**
     * Bindings generated by the runtime for use in query rules only. Differ from regular bindings in the way they are
     *  presented back to the user in string form
     */
    @JvmInline
    value class GeneratedBinding(val id: Int): Binding {
        override val name: String get() = " b${id}"
    }

    @JvmInline
    value class Exact(val term: Quad.Term): Subject, FixedPredicate, Object

    @JvmInline
    value class Alts(val allowed: List<FixedPredicate>): FixedPredicate

    @JvmInline
    value class Inverse(val predicate: FixedPredicate): FixedPredicate

    @JvmInline
    value class ZeroOrMore(override val element: FixedPredicate): RepeatingPredicate

    @JvmInline
    value class OneOrMore(override val element: FixedPredicate): RepeatingPredicate

}
