name: Publish documentation for release to Github Pages
on:
  release:
    types: [published]
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 'wrapper'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set version in env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate documentation for release
        run: ./gradlew --no-daemon :dokkaHtmlMultiModule
        env:
          GRADLE_OPTS: -Xms1g -Xmx4g

      - name: Publish documentation for release
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: build/dokka/htmlMultiModule
          target-folder: ${{ env.RELEASE_VERSION }}

      - name: Redirect stable to new release
        run: |
          echo "Redirecting stable to newly released version" 
          ln -sf $RELEASE_VERSION stable
          git add stable
          git commit -m "Redirect stable to new version $RELEASE_VERSION"
