name: Publish package to the Maven Central Repository
on:
  release:
    types: [published]
env:
  TARGET: release
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle 8.12
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12' # Quotes required to prevent YAML converting to number

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: gradle --no-daemon publishAllPublicationsToMavenCentralRepository
